server:
  port: 8001
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://62.234.116.48:3306/cloud01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: b405b406

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xing.springcloud.entities
